### ISSUE TITLE
org.hyperledger.transaction.SerializedTransaction is missing

### ISSUE THREAD

**Issue by yangjianguo** [hyperledger/fabric-api#1]
I got 2 complete error in org/hyperledger/transaction/Transaction.java:
Line 132 and Line 142:
SerializedTransaction cannot be resolved

Is that exists org.hyperledger.transaction.SerializedTransaction ?

**Comment by rjones-lf** [comment]
this is a read-only archive. please file a bug here: https://jira.hyperledger.org/
